import type { Metadata } from "next";
import { Montserrat, Merriweather } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { ModalProvider } from "@/providers/modal-provider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
});
const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <meta name="apple-mobile-web-app-title" content="Transom" />
      </head>
      <body
        className={`${montserrat.className} ${merriweather.variable} antialiased`}
      >
        <ModalProvider>
          <div className="flex flex-col min-h-screen pt-14 md:pt-[70px]">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}
